###########################################
# FOCRAFT.MSG - russ version
# Рецепты для крафта
# 
###########################################

# APAMk2 to APAMK2: Удалить,
# заместить скриптовым аналогом с FO4RP