###########################################
# FOHOLO.MSG - russ version
# Записи из голодисков и их названия
# 
###########################################

{1}{}{Голодиск успешно прочитан.}
{2}{}{Не удалось прочитать голодиск.}
{3}{}{Голодиск уже записан в Пиб-Бое.}
{4}{}{Память переполнена, сотрите ненужные записи.}
{5}{}{Запись удалена успешно.}
{6}{}{Не удалось удалить запись.}
{7}{}{Голодиск перезаписан.}
{8}{}{Не удалось перезаписать голодиск.}

#
# Format:
# Name - Number * 10
# Text - Number * 10 + 1

# 99999
# Последний корректный номер, после него текст берется из базы данных записей игроков.
# Голодиск для записей игроков.
{999990}{}{Голодиск}
{999991}{}{[Нет информации]}
