###########################################
# FOINTERNAL.MSG - russ version
# Внутренний файл движка (выглядит как заглушка)
# Не трогайте и/или не модифицируйте его
###########################################